### ISSUE TITLE
ScrollPrompt not scrolling on Blocks and Components 

### ISSUE THREAD

**Issue by StuartNicholls** [cgkineo/adapt-scrollPrompt#18]
### Subject of the issue
Block and Component scrolling don't seem to work for me. Perhaps something has changed with one of the core methods. But there looks like a number of small problems here and there. It looks like it needs something like `.attr('data-adapt-id')`or perhaps better to pass the id from the model like this `this.model.findRelativeModel('@block+1').get('_id')`. It might be worth allowing scrollPrompt to be added to articles too. 

### Your environment
Latest

### Steps to reproduce
Add scrollPrompt to blocks and components

**Comment by kirsty-hames** [comment]
I had a quick look at this as I thought it might be related to an issue I'm having. However, Block and Component scrolling works fine for me testing in latest FW v5.31.21 (Core v6.39.0) and FW v5.31.16 (Core v6.38.5). Are you getting any terminal/console errors? Device/browser specific?

**Comment by kirsty-hames** [comment]
> It might be worth allowing scrollPrompt to be added to articles too.

I agree. I think this can be raised as a separate issue.

**Comment by oliverfoster** [comment]
@StuartNicholls are you taking this? You're assigned.

**Comment by StuartNicholls** [comment]
@kirsty-hames, how odd. Hmm, Ill have to check the framework. I'd been checking this with compatibility with the new Hero plug-in so perhaps I'm on an older framework. However, it maybe better to use the model rather than how its currently done anyway. 

 I have found some other issues while looking at this. I'll raise the issues separately. What issues have you found?

**Comment by StuartNicholls** [comment]
@oliverfoster , yes I started this but found some other issues. Will raise separate tickets
