### ISSUE TITLE
Issues with scrollTo() in v5.7

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-scrollPrompt#7]
We recently noticed that upgrading to v5.7 of the framework breaks the scrollTo functionality in this plugin.  From my understanding, the target of scrollTo() must now be an Adapt object.

The following changes to the click event listener seem to work in v5.6 and v5.7 (haven't tested anything older):
```
    onScrollPromptClick: function(event) {
      /* set scroll to selector depending on model type */
      switch (this.model.get('_type')) {
        case 'course':
          var nextCO = this.model.findDescendantModels('contentObject')[0].attributes._id;
          Adapt.scrollTo('.' + nextCO, { duration: 800 });
          break;
        case 'page':
          var nextArticle = this.model.findDescendantModels('article')[0].attributes._id;
          Adapt.scrollTo('.' + nextArticle, { duration: 800 });
          break;
        case 'component':
          var nextBlock = this.model.findRelativeModel('@block +1').attributes._id;
          Adapt.scrollTo('.' + nextBlock, { duration: 800 });
          break;
      }
```
However, I'm unsure if there's a cleaner way to do this?  Also, for menus, this would scroll to the first contentObject menu item.  So, it would assume that the first contentObject is the topmost menu item that you would logically want to scroll to.

Worth mentioning that the addition of the 'component' type here is dependent on PR #4 .

**Comment by moloko** [comment]
@swashbuck this should be fixed with Adapt FW v5.7.1 (see https://github.com/adaptlearning/adapt_framework/issues/2928) but please reopen if not
